
services:

  bff:
    build: ./bff
    container_name: backend_for_frontend
    ports:
      - "4002:4002"
    depends_on:
      - backend
    env_file:
      - .env
    command: ["npm", "run", "up"]

  backend:
    build: ./backend
    container_name: nest_app
    ports:
      - "4000:4000"
    depends_on:
      - db
      - simulator
    env_file:
      - .env
    command: ["npm", "start"]

  frontend:
    build: ./frontend
    container_name: nuxt_app
    ports:
      - "3000:3000"
    depends_on:
      - bff
    env_file:
      - .env
    command: ["npm", "run", "dev"]

  simulator:
    build: ./simulator
    container_name: rust_simulator
    ports:
      - "4001:4001"
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

## The idea is to create one private network, where just the bff could request to the CRUD api.
## This approach should have some problems because can be insecure. Needs to create a register of the user requests.
## For the moment perhaps it's better just close the requests from outside of the container 