services:
  bff:
    build: ./bff
    container_name: backend_for_frontend
    ports:
      - "4002:4002"
    depends_on:
      - db
      - backend
      - simulator
    env_file:
      - .env.test
    command: ["npm", "run", "up"]
  backend:
    build: ./backend
    container_name: nest_app_test
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env.test
    command: ["npm", "run", "up"]

  frontend:
    build: ./frontend
    container_name: nuxt_app_test
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env.test
    command: ["npm", "run", "up"]

  simulator:
    build: ./simulator
    container_name: rust_simulator_test
    ports:
      - "4001:4001"

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
    - .env
    ports:
    - "5432:5432"

